# -- Prometheus & Grafana Configuration
kube-prometheus-stack:
  # 1. Stop trying to scrape the secure control plane components
  kubeControllerManager:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false

  # 2. Keep the good default rules, but disable the ones for the components above
  defaultRules:
    create: true
    rules:
      kubeControllerManager: false
      kubeScheduler: false
      etcd: false
      kubeProxy: false

  prometheus:
  # ADD THIS SERVICE BLOCK:
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: local-ip-pool
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path" 
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi

  grafana:
    enabled: true
    adminPassword: "admin" 
    service:
      type: LoadBalancer 
      annotations:
        metallb.universe.tf/address-pool: local-ip-pool
    persistence:
      enabled: true
      type: pvc
      storageClassName: "local-path"
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      finalizers:
        - kubernetes.io/pvc-protection
        
    # We purposefully leave this empty! 
    # ArgoCD will dynamically inject the Loki and Tempo URLs here.
    additionalDataSources: [] 

# -- Loki (Logs) Configuration
loki-stack:
  loki:
    persistence:
      enabled: true
      storageClassName: "local-path"
      size: 10Gi
  promtail:
    enabled: true 
    config:
      # We purposefully leave this empty!
      # ArgoCD will dynamically inject the Loki push URL here.
      clients: []
      
# -- Tempo (Traces) Configuration
tempo:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
  persistence:
    enabled: true
    storageClassName: "local-path"
    size: 10Gi
    
# -- Custom OpenTelemetry Collector Settings
otel:
  image:
    repository: "otel/opentelemetry-collector-contrib"
    tag: "0.100.0"
