image:
  repository: 192.168.41.90:8082/alumni-backend
  pullPolicy: Always
  tag: "v5"

service:
  port: 8000
  targetPort: 8000

env:
  NODE_ENV: "production"
  # KEYCLOAK_SERVER_URL: "http://keycloak-service.alumni-portal-dev.svc.cluster.local:8080"
  # This is the INTERNAL cluster URL used by the backend to fetch the public keys (jwksUri)
  # FIX 1: Add the /auth path so the backend can find the public keys : 30/05
  KEYCLOAK_JWKS_URI: "http://keycloak-service.{{ .Release.Namespace }}.svc.cluster.local:8080/auth/realms/application/protocol/openid-connect/certs"
  KEYCLOAK_REALM: "application"
  KEYCLOAK_CLIENT_ID: "backend-client"
  # FIX 2: Change http to https so it trusts your secure Keycloak tokens: 30/05
  KEYCLOAK_ISSUER: "https://192.168.41.88/auth/realms/application"
  #FIX 3: changing the service name and namespace : alumni-portal-dev
  NOTIFICATION_SERVICE_URL: "http://alumni-notification-api-service.{{ .Release.Namespace }}.svc.cluster.local:3000"
  KEYCLOAK_INTERNAL_URL: "http://keycloak-service.{{ .Release.Namespace }}.svc.cluster.local:8080"
  secretName: "alumni-secrets"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  MONGO_URI: "mongodb://admin:adminpassword@mongo-service.{{ .Release.Namespace }}.svc.cluster.local:27017/alumni?authSource=admin"