apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: alumni-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alumni-backend
  template:
    metadata:
      labels:
        app: alumni-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: PORT
              value: {{ .Values.service.targetPort | quote }}
            
            # --- Dynamic Cluster Routing URLs ---
            - name: MONGO_URI
              value: "mongodb://admin:adminpassword@mongo-service.{{ .Release.Namespace }}.svc.cluster.local:27017/alumni?authSource=admin"
            - name: KEYCLOAK_JWKS_URI
              value: "http://keycloak-service.{{ .Release.Namespace }}.svc.cluster.local:8080/auth/realms/application/protocol/openid-connect/certs"
            - name: NOTIFICATION_SERVICE_URL
              value: "http://alumni-notification-api-service.{{ .Release.Namespace }}.svc.cluster.local:3000"
            - name: KEYCLOAK_INTERNAL_URL
              value: "http://keycloak-service.{{ .Release.Namespace }}.svc.cluster.local:8080"
            
            # --- Standard Keycloak Configurations ---
            - name: KEYCLOAK_ISSUER
              value: {{ .Values.env.KEYCLOAK_ISSUER | quote }}
            - name: KEYCLOAK_REALM
              value: {{ .Values.env.KEYCLOAK_REALM | quote }}
            - name: KEYCLOAK_CLIENT_ID
              value: {{ .Values.env.KEYCLOAK_CLIENT_ID | quote }}
              
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi