apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-backend-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: alumni-backend
    # This variable will be provided by your Dev/Prod values.yaml
    release: {{ .Values.prometheus.release | default "alumni-observability-dev" }}
spec:
  selector:
    matchLabels:
      app: alumni-backend
  endpoints:
    - port: http-api
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
