apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-backend-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: alumni-backend
    # THE FIX: This now dynamically reads 'dev' or 'prod'
    release: {{ .Values.metrics.prometheusRelease }}
spec:
  selector:
    matchLabels:
      app: alumni-backend
  endpoints:
    - port: http-api
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s