apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-backend-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: alumni-backend
    release: alumni-observability-dev # Links directly to your Prometheus operator instance
spec:
  selector:
    matchLabels:
      app: alumni-backend
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s