apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: alumni-global-router
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/alumni-shared-gateway
  http:
    - match:
      - uri:
          prefix: /api
      route:
      - destination:
          host: alumni-backend-service.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: 8000
    - match:
      - uri:
          prefix: /auth
      route:
      - destination:
          host: keycloak-service.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: 8080
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: alumni-frontend-service.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: 80
