image:
  repository: ""
  pullPolicy: Always
  tag: ""

service:
  port: 3000
  targetPort: 3000

env:
  # --- Shared Configurations ---
  secretName: "alumni-secrets"

  # --- Placeholders for ArgoCD Overrides ---
  KAFKA_BROKER: ""