image:
  repository: "avitheg/alumni-backend"
  tag: "latest-dev" # Your Jenkins pipeline will update this

env:
  NODE_ENV: "development"
  KEYCLOAK_ISSUER: "https://192.168.41.88/auth/realms/application"