# A basic configuration to enable Grafana and set a default password
grafana:
  enabled: true
  adminPassword: "admin"
  ingress:
    enabled: true
    hosts:
      - grafana-dev.local

prometheus:
  prometheusSpec:
    # Lower retention for the dev cluster to save disk space
    retention: 2d