apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alumni-routing-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kanishkpandey18/git-infra-repo.git'
    targetRevision: main
    path: charts/shared-istio-routing
    # No values file needed because the VirtualService uses dynamic namespace routing
  destination:
    name: 'prod-rke2-cluster'
    namespace: alumni-portal-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true