velero:
  deployNodeAgent: true 
  upgradeCRDs: false
  
  # Resource overrides to fix "Insufficient CPU"
  nodeAgent:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    # Tolerations to fix "NodeAffinity" scheduling issues
    tolerations:
      - operator: Exists

  configuration:
    backupStorageLocation:
      - name: default
        provider: aws
        bucket: dev-cluster-backups
        config:
          region: minio
          s3ForcePathStyle: true
          s3Url: "http://192.168.41.37:32000"
  
  volumeSnapshotLocation:
    - name: default
      provider: aws

  kubectl:
    image:
      repository: docker.io/bitnami/kubectl
      tag: "1.30.0"
