image:
  repository: "avitheg/alumni-backend"
  tag: "observability-v2"

env:
  NODE_ENV: "production"
  KEYCLOAK_ISSUER: "https://jecrconnect.xyz/auth/realms/application"

  OTEL_SERVICE_NAME: "alumni-backend-prod"
  
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318"

  OTEL_LOG_LEVEL: "info"

metrics:
  # This guarantees the Prod Prometheus Operator finds this specific backend
  prometheusRelease: "alumni-observability-prod"

  # NODE_OPTIONS: "--require ./src/telemetry.js"
