apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: global-webhook-config
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  route:
    receiver: 'notification-api'
    groupBy: ['alertname', 'severity']
    groupWait: 30s 
    groupInterval: 5m 
    repeatInterval: 1h 
    routes:
      # --- THE FOOLPROOF GATEKEEPER ---
      # Intercept noisy system alerts and drop them into the void
      - match:
          alertname: PrometheusRuleFailures
        receiver: 'blackhole'
      - match:
          alertname: Watchdog
        receiver: 'blackhole'
      # --------------------------------
      
      # Route all other legitimate critical alerts to your microservice
      - match:
          severity: critical
        receiver: 'notification-api'
        
  receivers:
  - name: 'notification-api'
    webhookConfigs:
    - url: 'http://alumni-notification-api-service.alumni-portal-dev.svc.cluster.local:3000/api/v1/notify'
      sendResolved: true
      
  # --- THE VOID ---
  # A receiver with no webhook attached. It silently drops the alert.
  - name: 'blackhole'