apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 51.2.0 
    helm:
      valueFiles:
        # Pulls the configuration rules from your local repository
        - https://raw.githubusercontent.com/kanishkpandey18/git-infra-repo/main/argocd/dev/values/observability-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true